server {
    listen 80;
    server_name ec2-3-138-156-77.us-east-2.compute.amazonaws.com;

    root /var/www/Advanced_Software_Engineering/web;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/api/(.+\.php)$ {
        alias /var/www/Advanced_Software_Engineering/api/$1;
        include snippets/fastcgi-php.conf;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location /api/ {
        return 404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}
